// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/security/types.go
//
// Generated by this command:
//
//	mockgen -package=security -destination ../pkg/security/authenticacion_mocks.go -source ../pkg/security/types.go
//

// Package security is a generated GoMock package.
package security
