// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/common/environment/types.go
//
// Generated by this command:
//
//	mockgen -package=environment -destination ../pkg/common/environment/mocks.go -source ../pkg/common/environment/types.go
//

// Package environment is a generated GoMock package.
package environment

import (
	reflect "reflect"

	properties "github.com/guidomantilla/go-feather-lib/pkg/common/properties"
	gomock "go.uber.org/mock/gomock"
)

// MockEnvironment is a mock of Environment interface.
type MockEnvironment struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmentMockRecorder
	isgomock struct{}
}

// MockEnvironmentMockRecorder is the mock recorder for MockEnvironment.
type MockEnvironmentMockRecorder struct {
	mock *MockEnvironment
}

// NewMockEnvironment creates a new mock instance.
func NewMockEnvironment(ctrl *gomock.Controller) *MockEnvironment {
	mock := &MockEnvironment{ctrl: ctrl}
	mock.recorder = &MockEnvironmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironment) EXPECT() *MockEnvironmentMockRecorder {
	return m.recorder
}

// AppendPropertiesSources mocks base method.
func (m *MockEnvironment) AppendPropertiesSources(propertySources ...properties.PropertiesSource) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range propertySources {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AppendPropertiesSources", varargs...)
}

// AppendPropertiesSources indicates an expected call of AppendPropertiesSources.
func (mr *MockEnvironmentMockRecorder) AppendPropertiesSources(propertySources ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendPropertiesSources", reflect.TypeOf((*MockEnvironment)(nil).AppendPropertiesSources), propertySources...)
}

// PropertiesSources mocks base method.
func (m *MockEnvironment) PropertiesSources() []properties.PropertiesSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PropertiesSources")
	ret0, _ := ret[0].([]properties.PropertiesSource)
	return ret0
}

// PropertiesSources indicates an expected call of PropertiesSources.
func (mr *MockEnvironmentMockRecorder) PropertiesSources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PropertiesSources", reflect.TypeOf((*MockEnvironment)(nil).PropertiesSources))
}

// Value mocks base method.
func (m *MockEnvironment) Value(property string) EnvVar {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", property)
	ret0, _ := ret[0].(EnvVar)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockEnvironmentMockRecorder) Value(property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockEnvironment)(nil).Value), property)
}

// ValueOrDefault mocks base method.
func (m *MockEnvironment) ValueOrDefault(property, defaultValue string) EnvVar {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueOrDefault", property, defaultValue)
	ret0, _ := ret[0].(EnvVar)
	return ret0
}

// ValueOrDefault indicates an expected call of ValueOrDefault.
func (mr *MockEnvironmentMockRecorder) ValueOrDefault(property, defaultValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueOrDefault", reflect.TypeOf((*MockEnvironment)(nil).ValueOrDefault), property, defaultValue)
}
