name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Install
        run: make install
      - name: Generate
        run: make generate
      - name: Imports
        run: make sort-import
      - name: Format
        run: make format
      - name: Vet
        run: make vet
      - name: Lint
        run: make lint
      - name: Test
        run: make test